### ISSUE TITLE
Boss Idea, Tree boss

### ISSUE THREAD

**Issue by prodigiousking** [AngelArenaAllstars/angelarenaallstars.com#1]
Large circular arena with tree in the middle. Stage 1 tree drops projectile (apples) that roll in a straight line outwards (invoker meatball), as well as summons treants at regular intervals. The projectiles can be knocked back with an autoattack to damage treants and/or the tree. Stage 2 treants spawning cease but apples continue to spawn and roll faster, tree gains new attack where, (I know you said no flowery language but idk how to describe it otherwise,) from the center of the tree a slow burrowing animation begins one for every player, the trees roots slowly travel underground and somewhat/loosely home in on players. After 3 or so seconds the roots stop seeking their target if they have not hit yet, but if they hit they root the player making them prone to the apples and dealing damage (and maybe restoring the trees life?). Final stage the tree dies/breaks and falls over. From the stump a giant treant appears picks up the fallen tree to use as a club and this is stage three. The tree normally fights exactly like the boss from poke the angry ogre with constant ground slams and pursuing the last hero that hit him. However the boss has an animation that summons projectiles/apples from the sky in multiple small AOEs randomly (like sunstrikes) (this animation is channeled he doesnt attack while he performs it). In addition to other items killing this boss drops a few golden apples which act the same as a cheese.

**Comment by prodigiousking** [comment]
Sorry wrong place i am new to the website i will repost elsewhere

**Comment by salacryl** [comment]
Wrong place
